version: '3.3'

services:
    db:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - '5438:5432'
    api:
        container_name: puc-service-api
        build:
            context: .
        ports:
            - 3000:3000

volumes:
    pgdata:
